name: 1.1.$(Rev:r)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  location: 'centralus'
  adf_code_path: "$(Build.SourcesDirectory)/FactoryResources"
  adf_packages_file_path: "$(Build.SourcesDirectory)/DevOpsPipelines/"


stages:
  - stage: "publish_adf_artifact"
    displayName: Publish ADF Artifact
    variables:
      - name: azureSubscriptionId 
        value: 'ead6231b-67c2-496c-a2e5-d2ee7fb3491a'
      - name: dfResourceGroupName
        value: 'lws-cus-dev-dfcicd-rg'
      - name: factoryName 
        value: 'lws-cus-dev-dfcicd-adf'
    jobs:
      - job: 'ci'
        steps:
          - checkout: self
          - template: ./ci-pipeline.yml

  - stage: "deploy_adf_dev"
    displayName: Deploy ADF Dev
    dependsOn: ["publish_adf_artifact"]
    variables:
      - name: resource_group_name
        value: 'lws-cus-dev-dfcicd-rg'
      - name: azure_data_factory_name
        value: 'lws-cus-dev-dfcicd-adf'
      - name: azureSubscriptionId
        value: 'ead6231b-67c2-496c-a2e5-d2ee7fb3491a'
      - name: keyVaultBaeUrl
        value: 'https://lwscusdevdfcicdkeyvault.vault.azure.net/'
    jobs:
      - deployment: 'dev'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./cd-pipeline.yml
                  parameters:
                    serviceConnectionName: lws-poc-ado-sp

  - stage: "deploy_adf_stg"
    displayName: Deploy ADF Stg
    dependsOn: ["deploy_adf_dev"]
    variables:
      - name: resource_group_name
        value: 'lws-cus-stg-dfcicd-rg'
      - name: azure_data_factory_name
        value: 'lws-cus-stg-dfcicd-adf'
      - name: azureSubscriptionId
        value: 'ead6231b-67c2-496c-a2e5-d2ee7fb3491a'
      - name: keyVaultBaeUrl
        value: 'https://lwscusstgdfcicdkeyvault.vault.azure.net/'        
    jobs:
      - deployment: 'stg'
        environment: 'stg'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./cd-pipeline.yml
                  parameters:
                    serviceConnectionName: lws-poc-ado-sp #You would likely use a different service connection for each environment                     