name: 1.1.$(Rev:r)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  location: 'centralus'
  adf_code_path: "$(Build.SourcesDirectory)/FactoryResources"
  adf_packages_file_path: "$(Build.SourcesDirectory)/DevOpsPipelines/"


stages:
  - stage: "publish_adf_artifact"
    displayName: Publish ADF Artifact
    variables:
      - name: subscriptionId 
        value: 'ead6231b-67c2-496c-a2e5-d2ee7fb3491a'
      - name: resourceGroupName
        value: 'lws-goasy-poc-cus-rg'
      - name: factoryName 
        value: 'lws-goasy-poc-cus-factory'
    jobs:
      - job: 'ci'
        steps:
          - checkout: self
          - template: ./ci-pipeline.yml

  - stage: "deploy_adf_dev"
    displayName: Deploy ADF Dev
    variables:
      - name: resource_group_name
        value: 'lws-goasy-poc-cus-rg'
      - name: azure_data_factory_name
        value: 'lws-goasy-poc-cus-factory'
      - name: azureSubscription
        value: 'ead6231b-67c2-496c-a2e5-d2ee7fb3491a'
    jobs:
      - deployment: 'dev'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./cd-pipeline.yml
                  parameters:
                    serviceConnectionName: lws-poc-ado-sp

  - stage: "deploy_adf_stg"
    displayName: Deploy ADF Stg
    variables:
      - name: resource_group_name
        value: 'lws-goasy-test-cus-rg'
      - name: azure_data_factory_name
        value: 'lws-goasy-test-cus-factory'
      - name: azureSubscription
        value: 'ead6231b-67c2-496c-a2e5-d2ee7fb3491a'
    jobs:
      - deployment: 'stg'
        environment: 'stg'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./cd-pipeline.yml
                  parameters:
                    serviceConnectionName: lws-poc-ado-sp                     